DELETE http://localhost:3001/api/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZXguam9obnNvbkBleGFtcGxlLmNvbSIsImlkIjo0LCJpYXQiOjE3MjcyMDczMTYsImV4cCI6MTcyNzIxMDkxNn0.2XWBaCQ0OtNy5EraAolvuwTrHKytMFjzlDpbn7AE1bs
